### PR TITLE
Added Doxygen to public API

### PR DESCRIPTION
**Pull request by Akarinnnnn**
#33

### CODE REVIEW

**Comment by GiovanniDicanio** [comment]
Hi,

Thanks for your contribution. I’ll take a look later next week.



Il giorno gio 9 lug 2020 alle 11:22 Fa鸽 <notifications@github.com> ha
scritto:

**Comment by GiovanniDicanio** [comment]
Since this is a C++ project, can you please use C++ style Doxygen comments (e.g. `///`) instead of C-style `/* */`?
Or, is there any reason for you to prefer the C style?
Thanks.

**Comment by Akarinnnnn** [comment]
> Since this is a C++ project, can you please use C++ style Doxygen comments (e.g. `///`) instead of C-style `/** */`?
> Or, is there any reason for you to prefer the C style?
> Thanks.

Thank you for your feedback.

**Comment by GiovanniDicanio** [comment]
I may consider a similar addition if you used C++ style comments (`///`) as requested above, and especially if there were more details added to the Doxygen-style comments, e.g. parameter descriptions.

**Pull request closed without merging**
